### ISSUE TITLE
mgzip/mgzip/multiProcGzip.py has a typo in the name of the class

### ISSUE THREAD

**Issue by Hammit** [vinlyx/mgzip#3]
https://github.com/vinlyx/mgzip/blob/0b631a34d5405a80ae79f94dc52ec0e8b78a9a69/mgzip/multiProcGzip.py#L97

It should be MultiGzipFile, not MulitGzipFile

**Comment by vinlyx** [comment]
Thanks for your comment, this typo was fixed in v0.2.1.
