### ISSUE TITLE
mgzip not on pip?

### ISSUE THREAD

**Issue by vnckppl** [vinlyx/mgzip#4]
According to https://pypi.org/project/mgzip/#files I should be able to install mgzip via `pip install mgzip`, however, invoking this command results in:

> ERROR: Could not find a version that satisfies the requirement mgzip (from versions: none)
> ERROR: No matching distribution found for mgzip

What is preventing me from installing mgzip via pip?

**Comment by vinlyx** [comment]
Hi vnckppl,

Sorry for the late reply, but I just tested to install the latest version from pip. It works well for me (in Python 3.6.3), so I can't reproduced this issue. Which version of Python you are using?

**Comment by PJBoy** [comment]
Presumably vnckppl mistakenly used pip2 instead of pip3

**Comment by impredicative** [comment]
Because this issue is not reproducible, it can probably be closed.

**Comment by timhughes** [comment]
Can you try with https://github.com/pgzip/pgzip and if you still have the issue, please raise an issue there.

**Comment by vnckppl** [comment]
It is working with `python3 -m pip install mgzip`. Thanks!
