### ISSUE TITLE
gzip decompression

### ISSUE THREAD

**Issue by F-hertz** [vinlyx/mgzip#5]
Hello

First, thank you for your initiative.
Got a question, when i try to decompress a gzfile it use only one CPU (got 24 cpus), do you have an example that can decompress gzfile to a destination file ?

Anyway thanks.

**Comment by cielavenir** [comment]
I happened to see this just now.

The very original gzip format does not support parallel decompression and specific format is required. There _have been_ several attempts to invent such formats (This mgzip is one of them).
