### ISSUE TITLE
can it perform random block access ?

### ISSUE THREAD

**Issue by bioinfornatics** [vinlyx/mgzip#8]
Dear,

Can it perform random block access ?
How to index the compressed file ?

Thanks

**Comment by vinlyx** [comment]
Hi @bioinfornatics,

Sorry for the late reply. Yes, it is able to perform random block access, the block size and data size information is perserved in the extra field in gzip header.

You can use get index method to build_index method to construct a index file, then you can seek to random position with ~O(1) performance (constant time).

BTW, please notes that the indexing step only go through all the header of gzip block, it doesn't need to decompress the data, so it should be faster than common indexing method.

**Comment by bioinfornatics** [comment]
perfect thanks @vinlyx
